/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 09 16:52:01 GMT 2017
 */

package model.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import model.impl.CompteCourant;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompteCourant_ESTest extends CompteCourant_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CompteCourant compteCourant0 = new CompteCourant((String) null);
      double double0 = compteCourant0.deposit(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CompteCourant compteCourant0 = new CompteCourant("wer:");
      double double0 = compteCourant0.deposit(1411.0);
      assertEquals(1411.0, compteCourant0.getBalance(), 0.01);
      assertEquals(1411.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CompteCourant compteCourant0 = new CompteCourant("", 352.35);
      compteCourant0.withdraw(352.35);
      try { 
        compteCourant0.withdraw(352.35);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Overdraft. Current balance = 0.0
         //
         verifyException("model.impl.CompteCourant", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CompteCourant compteCourant0 = new CompteCourant("Owner: ");
      double double0 = compteCourant0.deposit((-1.0));
      assertEquals((-1.0), compteCourant0.getBalance(), 0.01);
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CompteCourant compteCourant0 = new CompteCourant("");
      double double0 = compteCourant0.withdraw((-425.608));
      assertEquals(425.608, compteCourant0.getBalance(), 0.01);
      assertEquals(425.608, double0, 0.01);
  }
}
